config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[index show] do
    resources :reviews, only: %i[new create]
    resources :chatrooms, only: %i[create]
  end

  resources :availabilities, only: %i[new create]

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: %i[new create]
  end

  get "/my_profile", to: "users#my_profile", as: :my_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :requester, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: "User"

  validates :description, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews, dependent: :destroy
  has_many :chatrooms
  has_many :messages # maybe we dont need this?
  has_many :availabilities
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  def chatrooms
    Chatroom.where(requester: self).or(Chatroom.where(receiver: self))
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def types_of_climbing
    types = []
    types << 'Bouldering' if bouldering?
    types << 'Sport Climbing' if sport_climbing?
    types << 'Top Roping' if top_roping?
    types << 'Trad Climbing' if trad_climbing?
    p self
    p types
    types
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:location, :level, :bouldering, :sport_climbing, :top_roping, :trad_climbing])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
  
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController

  def new
    @availability = Availability.new
  end

  def create
    @availability = Availability.new(availability_params)
    @availability.user = current_user
    if @availability.save
      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def availability_params
    params.require(:availability).permit(:date, :begin_time, :end_time)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  # route controller view

  def index
    @chatrooms = current_user.chatrooms
    @messages = Message.all
    # To do - @message = Message.where("chatroom_id: ?", @chatroom.id).last
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @chatrooms = Chatroom.all
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.requester = current_user
    if @chatroom.save
      redirect_to chatroom_path(@chatroom)
    else
      render "users/show"
    end
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:receiver_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ActionCable.server.broadcast("chatroom-#{@chatroom.id}",
        render_to_string(partial: 'messages/message',
          locals: {message: @message})
      )
      redirect_to chatroom_path(@chatroom)
    else
      render 'chatrooms/show', status: unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @users = User.first(4)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
      flash[:notice] = "Account succesfully updated"
      my_profile_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @review.author = current_user
    @user = User.find(params[:user_id])
    @review.user = @user
    if @review.save
      redirect_to user_path(@user)
    else
      render 'users/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Code may change dependent on the exact search functionality we want.
  def index
    @users = User.all

    @users = @users.near(params[:location], 5) if params[:location].present? && params[:location] != ""

    # filters
    @users = @users.where("gender ILIKE ?", params[:gender]) if params[:gender].present? && params[:gender] != ""
    @users = @users.where("level ILIKE ?", params[:level]) if params[:level].present? && params[:level] != ""
    @users = @users.where("bouldering = ?", params[:bouldering]) if params[:bouldering].present? && params[:bouldering] != ""
    @users = @users.where("sport_climbing = ?", params[:sport_climbing]) if params[:sport_climbing].present? && params[:sport_climbing] != ""
    @users = @users.where("top_roping = ?", params[:top_roping]) if params[:top_roping].present? && params[:top_roping] != ""
    @users = @users.where("trad_climbing = ?", params[:trad_climbing]) if params[:trad_climbing].present? && params[:trad_climbing] != ""

    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_path("icon_climbing.png")
      }
    end
  end

  def show
    @user = User.find(params[:id])
    @review = Review.new
    @chatroom = Chatroom.new
    @markers = [
      {
        lat: @user.latitude,
        lng: @user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: @user }),
        image_url: helpers.asset_path("icon_climbing.png")
      }
    ]
  end

  def my_profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/meta_tags_helpers.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/availabilities/new.html.erb
<h1>Add your availability!</h1>

<%= simple_form_for(@availability) do |f| %>
<%= f.input :date %>
<%= f.input :begin_time %>
<%= f.input :end_time %>
<%= f.submit "Set my availability", class: "btn btn-danger btn-lg" %>
<% end %>

app/views/chatrooms/index.html.erb
<div class="container">
  <h1 class="heading fw-bolder text-center"><strong> My Inbox </strong></h1>
  <br>
    <% @chatrooms.each do |chatroom| %>
    <%= link_to chatroom_path(chatroom) do %>
    <div class="inbox-chats">
      <% participant = chatroom.requester == current_user ? chatroom.receiver : chatroom.requester %>
      <%= cl_image_tag participant.photo.key %>
        <div class="inbox-user fw-bolder">
          <p>
          <span style="font-weight: bolder; font-size: 30px;"> <%= participant.full_name %> </span> </p>
          <% if chatroom.messages.count > 0 %>
          <p><%= chatroom.messages.order(:created_at).last.created_at.strftime("%a %b %e at %l:%M %p") %></p>
          <% end %>
        </div>
    </div>
      <% end %>
    <% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container">
  <div class="chat-div" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>" data-user="<%= current_user.id %>">
    <% participant = @chatroom.requester == current_user ? @chatroom.receiver : @chatroom.requester %>
    <h1 id="name"> <%= cl_image_tag participant.photo.key, class: "avatar dropdown-toggle" %> <%= participant.full_name %> </h1>
    <div class="container chatroom" >
      <div class="flex-grow-1">
        <br>

        <div class="messages flex-grow-1" data-chatroom-subscription-target="messages">

          <% @chatroom.messages.each do |message| %>
            <%= render 'messages/message', message: message %>
          <% end %>

        </div>
        <br>
      </div>
    </div>

      <%= simple_form_for [@chatroom, @message],
      html: {class: "d-flex", data: {chatroom_subscription_target: "form"}} do |f|
      %>
        <%= f.input :content,
          label: false,
          placeholder: "Message #{participant.first_name}...",
          wrapper_html: {class: "flex-grow-1"}, input_html: { class: "input-message"}
        %>
        <%= f.submit "Send", class:"btn btn-primary mb-3 margin-left"%>
      <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= asset_path('stronghold_2.jpg') %>)">
  <div class="container text-center">
    <br>
      <p>Find a climbing <span data-controller="typed-js"></span></p>
      <br>
      <div class="wrapper">
      <%= link_to "LET'S GO", users_path, class: "button" %>
      </div>
  </div>
</div>

<div class="hero">
  <div class="homepage-testimonials mt-5">
    <div class="container">
      <div class="row gx-5">
        <div class="col-4">
            <div class="row">
              <div class="col-4">
                <img src='https://ca.slack-edge.com/T02NE0241-U03BVCNU1EY-c36d009ede6b-512' alt=''>
              </div>
              <div class="col-8">
                <p>⭐️⭐️⭐️⭐️⭐️<br>"I just started climbing and wanted to make friends in the climbing community. Belay Buddies helped me do that!"</p>
                <p class="text-right"><strong>Maryam Fazlali</strong><br>New Climber</p>
              </div>
            </div>
          </div>
          <div class="col-4">
            <div class="row">
              <div class="col-4">
                <img src='https://ca.slack-edge.com/T02NE0241-U03CCD0N9DE-ee10df33cd0d-512' alt=''>
              </div>
              <div class="col-8">
                <p>⭐️⭐️⭐️⭐️⭐️<br> "Met some of my best friends on Belay Buddies!"</p><br>
                <p class="text-right"><strong>Usman Akram</strong><br>Handsome Climber</p>
              </div>
            </div>
          </div>
          <div class="col-4">
            <div class="row">
              <div class="col-4">
                <%= image_tag('janja.jpg') %>
              </div>
              <div class="col-8">
                <p>⭐️⭐️⭐️⭐️⭐️<br>"I just love being able to share my passion for climbing with other people. Belay Buddies let's me do that!"</p>
                <p class="text-right"><strong>Janja Garnbret</strong><br>Climbing Olympic Gold Medalist</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <span class="curve"></span>
  </div>
</div>

<div class="hero">
  <div class="homepage-grid">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 justify-content-center text-center">
          <h1>How it works</h1>
        </div>
        <div class="row align-content-center">
          <%# <div class="col text-center">
            <h1>1</h1>
          </div> %>
          <div class="col-6 d-flex justify-content-center align-items-center">
            <h3>Find climbers in your area or city</h3>
          </div>
          <div class="col d-flex justify-content-center">
            <%= image_tag('strong_woman.jpg') %>
          </div>
        </div>
        <div class="row">
          <%# <div class="col text-center">
            <h1>2</h1>
          </div> %>
          <div class="col-6 d-flex justify-content-center align-items-center">
            <h3>Send them a message and wait for their response</h3>
          </div>
          <div class="col d-flex justify-content-center">
            <%= image_tag('castle_climbing.jpg') %>
          </div>
        </div>
        <div class="row">
          <%# <div class="col text-center">
            <h1>3</h1>
          </div> %>
          <div class="col-6 d-flex justify-content-center align-items-center">
            <h3>Meet up with them and climb</h3>
          </div>
          <div class="col d-flex justify-content-center">
            <%= image_tag('happy_climbing_couple_2.jpg') %>
          </div>
        </div>
      </div>
    </div>
  </div>
    <span class="curve"></span>
</div>

<div class="container text-center mt-2">
  <h1>Recently Joined Buddies</h1>
    <div class="cards text-center" style="display:grid; grid-template-columns: 1fr 1fr 1fr 1fr;">
      <% @users.each do |user| %>
        <div class="position-relative mt-4">
          <%= link_to user_path(user) do %>
            <div class="card-user">
              <%= cl_image_tag user.photo.key %>
              <h2 class="user-name mt-3 fw-bolder"><%= user.full_name %></h2>
                <div class="card-user-infos">
                  <p>📍<%= user.location %></p>
                    <% user.types_of_climbing.each do |type_of_climbing| %>
                    <p class="mb-0"><%= type_of_climbing %></p>
                  <% end %>
                </div>
              </div>
            <% end %>
            <div class="d-flex justify-content-center align-items-center card-btn p-0 fw-bolder">
              <% chatroom = Chatroom.where(receiver: user, requester: current_user).first || Chatroom.where(receiver: current_user, requester: user).first %>
              <% if chatroom %>
                <%= link_to 'Message', chatroom_path(chatroom), class: "btn" %>
              <% else %>
                <%= simple_form_for [user, Chatroom.new] do |f| %>
                  <%= f.input :receiver_id, as: :hidden, input_html: { value: user.id } %>
                  <%= f.submit 'Message', class: 'btn' %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>

    <%# <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="searchbar">
          <input class="search_input" type="text" name="" placeholder="Look for Buddies...">
          <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
        </div>
      </div>
    </div> %>

<%# <div class="hero">

   <h1>Full-Width Section with a Convex Curve Bottom Divider</h1>
   <h3>Using border radius and a pseudo class clipped by overflow: hidden.</h3>
  <span class="curve"></span>

</div> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top"
  data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar"
>
  <div class="container-fluid">
  <%= link_to root_path, class: "navbar-brand mx-3" do %>
      <%= image_tag ('logo.png') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto fs-5 fw-bolder">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Buddies", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown fs-4">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", my_profile_path, class: "dropdown-item fw-bolder" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item fw-bolder" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
    <div class="container">
      <div class="row searchbar-wrapper", style="margin-left:12px">

      <%= form_tag users_path, method: :get, class: "d-flex justify-content-center" do %>
        <%= text_field_tag :location, params[:location], value:params[:location], class: "form-control fs-6", style: "width:180px; min-height:40px; margin-right:5px", placeholder: "Enter Location"%>
        <%= select_tag "gender", options_for_select(["Male", "Female", "Other"]), class: "form-control fs-6", style: "width:180px; min-height:40px; margin-right:5px", prompt:"Select Gender"%>
        <%= select_tag "level", options_for_select(["Beginner", "Intermediate", "Advanced"]), class: "form-control fs-6", style: "width:180px; min-height:40px; margin-right:5px", prompt:"Select Level"%>
        <div class="form-check">
          <%= label_tag "bouldering", "Bouldering: ", class: "form-control-1" %>
          <%= check_box_tag "bouldering", true %>
          <%= label_tag "sport_climbing", "Sport Climbing: " %>
          <%= check_box_tag "sport_climbing", true %>
          <%= label_tag "top_roping", "Top Roping: " %>
          <%= check_box_tag "top_roping", true %>
          <%= label_tag "trad_climbing", "Trad Climbing: " %>
          <%= check_box_tag "trad_climbing", true %>
        </div>
        <%= submit_tag "Search", class: "btn btn-lg" %>
      <% end %>
    </div>

<%# <h1 class="heading fw-bolder text-center">🧍‍♂️<strong> Climbing Buddies Matches </strong>🧍‍♀️</h1> %>
    <div class="main-container">
      <%# <div class="d-flex justify-content-between"> %>
        <div style="width: 50%">
          <div class="cards text-center">
              <% @users.each do |user| %>
                <div class="position-relative">
                  <%= link_to user_path(user) do %>
                    <div class="card-user">
                      <%= cl_image_tag user.photo.key %>
                      <h2 class="user-name mt-3 fw-bolder"><%= user.full_name %></h2>
                      <div class="card-user-infos">
                        <p>📍<%= user.location %></p>
                          <% user.types_of_climbing.each do |type_of_climbing| %>
                          <p class="mb-0"><%= type_of_climbing %></p>
                          <% end %>
                      </div>
                    </div>
                  <% end %>
            <div class="d-flex justify-content-center align-items-center card-btn p-0 fw-bolder">
              <% chatroom = Chatroom.where(receiver: user, requester: current_user).first || Chatroom.where(receiver: current_user, requester: user).first %>
              <% if chatroom %>
                <%= link_to 'Message', chatroom_path(chatroom), class: "btn" %>
              <% else %>
                <%= simple_form_for [user, Chatroom.new] do |f| %>
                  <%= f.input :receiver_id, as: :hidden, input_html: { value: user.id } %>
                  <%= f.submit 'Message', class: 'btn' %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <div style="width: 50%">
    <%# <h1 class="heading text-warning fw-bolder text-center text-light">📍 <strong> Map of Your Matches </strong> 🌎</h1> %>
    <div id="map" style="width: 100%; top: 150px; height: calc(100vh - 200px);"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>
  </div>

app/views/users/my_profile.html.erb
  <div class="container text-center typed-heading">
    <br>
      <h1>Welcome <span data-controller="typed-js"></span></h1>
      <br>
      <div class="wrapper">
      <%#= link_to "LET'S GO", users_path, class: "button" %>
      </div>
  </div>

<div class="users-show">
  <div class="container">
    <div class="row col-12 user-info text-center">
      <div class="col-6">
        <%= cl_image_tag @user.photo.key, class: "users-image" %>
      </div>

      <div class="profile-info col-6">
        <h1 style="padding-bottom: 2rem; padding-top: 2rem;">Hi, <%= @user.first_name.titleize %></h1>
        <div class="row justify-content-center">
          <div class="col-3">
            <div class="d-flex align-items-center justify-content-start">
              <% if @user.gender == "male" %>
                <i class="fa-solid fa-mars me-2"></i>
              <% else %>
                <i class="fa-solid fa-venus text-warning me-2"></i>
              <% end %>
              <p class="fs-6 mb-0"><%= @user.age %></p>
            </div>
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-arrow-up-wide-short me-2"></i>
              <p class="fs-6 mb-0"><%=" "%><%= @user.level.capitalize %></p>
            </div>
          </div>
          <div class="col-5">
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-map-pin me-2"></i>
              <p class="fs-6 mb-0"><%= @user.location %></p>
            </div>
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-mountain me-2"></i>
              <p class="fs-6 mb-0"><%= @user.types_of_climbing.join(", ") %></p>
            </div>
          </div>
        </div>
        <br>
        <br>
            <%= link_to 'Edit My Profile', edit_user_registration_path, class: "btn" %>
      </div>

    <div class="row my-3 justify-content-center">
      <div class="col-6 text-center">
        <div class="", id="user-review-box">
          <h3 class="text-center fs-2 fw-bolder mt-1">Previous Reviews</h3>
          <% @user.reviews.each do |review| %>
            <p class=fs-6><%= review.description %></p><p class=fs-6><%='<i class="fas fa-star star-yellow"></i>'.html_safe * review.rating %><%=" " %><%= time_ago_in_words( review.created_at) %> ago</p>
            <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
    <div class="col-6 text-center">

    </div>

    <br>
    <p class="fs-6 mt-2"><%= link_to "Back to Climbers", users_path, class: "text-light" %></p>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="users-show">
  <div class="container">
    <div class="row col-12 user-info text-center">
      <div class="col-6">
        <%= cl_image_tag @user.photo.key, class: "users-image" %>
        <h1 style="padding-bottom: 0.6rem;">Hi, I'm <%= @user.first_name.titleize %></h1>
        <div class="row justify-content-center">
          <div class="col-3">
            <div class="d-flex align-items-center justify-content-start">
              <% if @user.gender == "male" %>
                <i class="fa-solid fa-mars me-2"></i>
              <% else %>
                <i class="fa-solid fa-venus text-warning me-2"></i>
              <% end %>
              <p class="fs-6 mb-0"><%= @user.age %></p>
            </div>
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-arrow-up-wide-short me-2"></i>
              <p class="fs-6 mb-0"><%=" "%><%= @user.level.capitalize %></p>
            </div>
          </div>
          <div class="col-5">
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-map-pin me-2"></i>
              <p class="fs-6 mb-0"><%= @user.location %></p>
            </div>
            <div class="d-flex align-items-center justify-content-start">
              <i class="fa-solid fa-mountain me-2"></i>
              <p class="fs-6 mb-0"><%= @user.types_of_climbing.join(", ") %></p>
            </div>
          </div>
        </div>
        <% chatroom = Chatroom.where(receiver: @user, requester: current_user).first || Chatroom.where(receiver: current_user, requester: @user).first %>
        <% if chatroom %>
          <%= link_to 'Message', chatroom_path(chatroom), class: "btn btn-contrast btn-lg mt-2 fw-bolder" %>
        <% else %>
          <%= simple_form_for [@user, @chatroom] do |f| %>
            <%= f.input :receiver_id, as: :hidden, input_html: { value: @user.id } %>
            <%= f.submit 'Message', class:"btn btn-lg btn-contrast mt-2 fw-bolder" %>
          <% end %>
        <% end %>
      </div>

      <div class="col-6">
        <div id="map" style="width: 100%; height: 100%;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>



    </div>
    <div class="row col-6">
    </div>

    <div class="row col-12">
      <div class="col-6 text-center">


      <div class="row col-12 user-info">

        <div class="">
          <h3 class="text-center fs-2 fw-bolder mt-1">Review this Climber</h3>
          <% if @user.reviews.empty? %>
            <div class="d-flex justify-content-center align-items-center">
              <small><em class="text-muted">Be the first one to review this climber</em></small>
            </div>
          <% end %>
          <%= simple_form_for [@user, @review] do |f| %>
            <%= f.input :description, placeholder: "Add your review here...", input_html: { class: 'fs-6 pt-3 user-reviews' } %>
            <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "Select your rating", input_html: { class: "form-control fs-6 user-reviews", data: { controller: "jquery-bar-rating" } } %>
            <%= f.submit class:"btn" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-6 text-center">
      <div class="", id="user-review-box">
        <h3 class="text-center fs-2 fw-bolder mt-1">Previous Reviews</h3>
        <% @user.reviews.each do |review| %>
        <div class="d-flex flex-column align-items-start py-2 px-5">
          <p class="mb-2 fw-bold"> <%= cl_image_tag review.author.photo.key, class: "avatar" %> <%= review.author.full_name %> </p>
          <p class="mb-0 grey-text"><%='<i class="fas fs-6 fa-star star-yellow"></i>'.html_safe * review.rating %><%=" " %><%=time_ago_in_words( review.created_at) %> ago</p>
          <h6 class="py-3 text-start"><%= review.description.capitalize %></h6>
        <br>
        </div>
        <% end %>
      </div>
    </div>
    <br>
    <p class="fs-6 mt-2"><%= link_to "Back to Climbers", users_path, class: "text-light" %></p>
  </div>
</div>
</div>